### ISSUE TITLE
Could you add a README to this repo to help new users?

### ISSUE THREAD

**Issue by mjnivarel** [JohnDeere/MyJohnDeereAPI-OAuth-Java-Client#6]

**Comment by anthonye2007** [comment]
What are the main classes I should look at?  Please add to Readme!

**Comment by dv30371** [comment]
Thanks for the suggestion, We will add the information.

**Comment by joshuajcarson** [comment]
README.MD added at https://github.com/JohnDeere/MyJohnDeereAPI-OAuth-Java-Client/blob/master/README.md, so the basic install and first call should be visible now. Let us know if you are looking for even more from a readme @anthonye2007
